In [1]:
import pandas as pd

from protocols import graphs

%load_ext autoreload
%autoreload 2

In [2]:
who_drugs = list(pd.read_csv('data/who2_drugs.csv').drug)
who_drugs

['INH',
 'RIF',
 'PZA',
 'EMB',
 'BDQ',
 'LZD',
 'MXF',
 'LEV',
 'CFZ',
 'DLM',
 'AMI',
 'STM',
 'ETH',
 'KAN',
 'CAP']

In [3]:
who_results = pd.read_csv('data/WHO2-Annex1-table.csv')
who_results = who_results.iloc[::-1]
who_results = who_results[who_results.FRS==0.75]
who_results
who1_results = who_results[who_results.catalogue=='WHO1']
who2_results = who_results[who_results.catalogue=='WHO2']
who1_results

,drug,catalogue,FRS,sensitivity,specificity,PPV,sensitivity_low,sensitivity_high,specificity_low,specificity_high,PPV_low,PPV_high
42,CAP,WHO1,0.75,66.4,97.8,80.1,64.3,68.4,97.6,98.1,78.2,82.0
39,KAN,WHO1,0.75,75.1,96.5,78.7,73.6,76.5,96.3,96.8,77.2,80.0
36,ETH,WHO1,0.75,72.5,86.6,64.4,71.3,73.7,86.1,87.2,63.2,65.7
33,STM,WHO1,0.75,79.2,94.1,89.9,78.4,80.0,93.7,94.5,89.2,90.5
30,AMI,WHO1,0.75,72.9,98.1,81.3,71.1,74.6,97.9,98.3,79.6,82.9
27,DLM,WHO1,0.75,4.4,100.0,84.6,2.2,7.7,99.9,100.0,54.6,98.1
24,CFZ,WHO1,0.75,0.0,100.0,0.0,0.0,0.5,100.0,100.0,0.0,0.0
21,LEV,WHO1,0.75,83.7,97.1,88.7,82.7,84.6,96.9,97.3,87.8,89.5
18,MXF,WHO1,0.75,85.0,93.8,74.5,83.8,86.1,93.4,94.1,73.2,75.8
15,LZD,WHO1,0.75,27.3,99.8,78.5,22.8,32.1,99.8,99.9,70.4,85.2
12,BDQ,WHO1,0.75,0.0,100.0,0.0,0.0,0.4,100.0,100.0,0.0,0.0
9,EMB,WHO1,0.75,83.8,91.2,71.6,83.1,84.6,90.9,91.5,70.7,72.4
6,PZA,WHO1,0.75,73.7,98.0,90.8,72.4,75.0,97.8,98.2,89.8,91.7
3,RIF,WHO1,0.75,93.3,96.9,94.2,92.9,93.7,96.7,97.1,93.9,94.6
0,INH,WHO1,0.75,91.0,98.1,97.3,90.6,91.4,97.9,98.2,97.1,97.5

In [4]:
results_training = pd.read_csv('results/performance/whov1_whov2_cat1_training.csv')
results_training.DRUG = results_training.DRUG.astype('category')
results_training.DRUG = results_training.DRUG.cat.set_categories(who_drugs)
results_training.sort_values(['DRUG','catalogue'], inplace=True)
results_training = results_training.iloc[::-1]
results_training[:6]

,Unnamed: 0,DRUG,catalogue,SENSITIVITY,SPECIFICITY,COVERAGE,SENSITIVITY2,SPECIFICITY2
11,11,CAP,catomatic_v1,0.844141,0.975157,0.920088,0.811816,0.977242
10,10,CAP,WHOv2,0.816027,0.974964,0.956359,0.791028,0.976088
9,9,CAP,WHOv1,0.814059,0.975345,0.957795,0.785558,0.976403
26,26,KAN,catomatic_v1,0.832658,0.925637,0.953942,0.828818,0.929395
25,25,KAN,WHOv2,0.800236,0.973200,0.932404,0.780403,0.975136
24,24,KAN,WHOv1,0.799764,0.973411,0.939096,0.780403,0.975136

In [5]:
results_validation = pd.read_csv('results/performance/whov1_whov2_cat1_validation.csv')
results_validation.DRUG =results_validation.DRUG.astype('category')
results_validation.DRUG = results_validation.DRUG.cat.set_categories(who_drugs)
results_validation.sort_values(['DRUG','catalogue'], inplace=True)
results_validation = results_validation.iloc[::-1]
results_validation[:6]

,Unnamed: 0,DRUG,catalogue,SENSITIVITY,SPECIFICITY,COVERAGE,SENSITIVITY2,SPECIFICITY2
11,11,CAP,catomatic_v1,0.795699,0.962179,0.926505,0.742475,0.965010
10,10,CAP,WHOv2,0.806780,0.960943,0.956019,0.795987,0.962911
9,9,CAP,WHOv1,0.795699,0.963864,0.946181,0.742475,0.965710
26,26,KAN,catomatic_v1,0.919614,0.954754,0.931049,0.909380,0.958855
25,25,KAN,WHOv2,0.917874,0.969595,0.911101,0.906200,0.973166
24,24,KAN,WHOv1,0.917874,0.970080,0.921509,0.906200,0.973166

In [6]:
graphs.plot_bar_who(results_training,who_results,'figs/performance/bar-training-who1-who2.pdf', who_drugs)
graphs.plot_bar_who(results_validation,who_results,'figs/performance/bar-validation-who1-who2.pdf', who_drugs)

In [7]:
graphs.plot_bar_catomatic(results_training, 'figs/performance/bar-training-who1-who2-cat1.pdf', who_drugs)
graphs.plot_bar_catomatic_coverage(results_training, 'figs/performance/bar-training-who1-who2-cat1-coverage.pdf', who_drugs)

In [8]:
graphs.plot_bar_catomatic(results_training, 'figs/performance/bar-training-who1-who2-cat1-binary.pdf', who_drugs, sensitivity='SENSITIVITY2', specificity='SPECIFICITY2')

In [9]:
graphs.plot_bar_catomatic(results_validation, 'figs/performance/bar-validation-who1-who2-cat1.pdf', who_drugs)
graphs.plot_bar_catomatic_coverage(results_validation, 'figs/performance/bar-validation-who1-who2-cat1-coverage.pdf', who_drugs)

In [10]:
graphs.plot_bar_catomatic(results_validation, 'figs/performance/bar-validation-who1-who2-cat1-binary.pdf', who_drugs, sensitivity='SENSITIVITY2', specificity='SPECIFICITY2')